### PR TITLE
Fix reference error.

### PR DESCRIPTION
**Pull request by yhirokawa**

### CODE REVIEW

**Comment by ayamada224** [comment]
Thanks, yhirokawa san. 
In your changes, I found one mistake at  the 39-th line in install_and_run.rst, that is, 

The newest version of SALMON can be downloaded from `download page <XXXXXX>`_.

XXXXX is the link of download page of SALMON, but the link of cmake is put here in your change probably by mistake. The other your changes are OK. Could you please fix the link?

**Comment by yhirokawa** [comment]
Thanks, I corrected it just now.
I look the following error message when building `install_and_run.rst`

    Duplicate explicit target name: "download page"

"Anonymous hyperlink" solves this error: https://stackoverflow.com/questions/5464627/how-to-have-same-text-in-two-links-with-restructured-text/14067756#14067756

**Comment by ayamada224** [comment]
I noticed your corrected parts have two "_", that is, "__" instead of single "_", like
`download page <http://salmon-tddft.jp/download.html>`__
maybe this one is the reason??

**Comment by yhirokawa** [comment]
double underscore ("__") means the anonymous hyperlink.

**Comment by ayamada224** [comment]
I compiled with "make.bat html" at my own windows PC, but I didn't find error about what you found ....
How did you find the error?

**Comment by yhirokawa** [comment]
I checked the following environment.

- Sphinx 1.7.6 with Python 2.7.14
- Mac OS X 10.13.6

... and console logs when compiling html files.

```
$ make html
Running Sphinx v1.7.6
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 0 added, 2 changed, 0 removed
reading sources... [100%] install_and_run
/Users/hirokawa/salmon-documents/source/install_and_run.rst:4: WARNING: Duplicate explicit target name: "download page".
/Users/hirokawa/salmon-documents/source/install_and_run.rst:4: WARNING: Duplicate explicit target name: "download page".
/Users/hirokawa/salmon-documents/source/install_and_run.rst:451: WARNING: Duplicate explicit target name: "cmake".
/Users/hirokawa/salmon-documents/source/install_and_run.rst:452: WARNING: Duplicate explicit target name: "download page".
looking for now-outdated files... none found
...
```

**Comment by ayamada224** [comment]
As reference, my environment is
Sphinx 1.7.6 with Python 3.7.0
Windows 10

**Pull request merged**
